"""init_tables

Revision ID: 001
Revises: 
Create Date: 2026-02-22 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets_meta',
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_markets_meta_condition_id'), 'markets_meta', ['condition_id'], unique=False)
    op.create_index(op.f('ix_markets_meta_slug'), 'markets_meta', ['slug'], unique=True)
    
    op.create_table('inventory_ledger',
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('yes_exposure', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('no_exposure', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets_meta.condition_id'], ),
    sa.PrimaryKeyConstraint('market_id')
    )
    
    op.create_table('orders_journal',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=True),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('size', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'FILLED', 'CANCELED', 'FAILED', name='orderstatus'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets_meta.condition_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_journal_market_id'), 'orders_journal', ['market_id'], unique=False)
    op.create_index(op.f('ix_orders_journal_order_id'), 'orders_journal', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_journal_order_id'), table_name='orders_journal')
    op.drop_index(op.f('ix_orders_journal_market_id'), table_name='orders_journal')
    op.drop_table('orders_journal')
    
    op.drop_table('inventory_ledger')
    
    op.drop_index(op.f('ix_markets_meta_slug'), table_name='markets_meta')
    op.drop_index(op.f('ix_markets_meta_condition_id'), table_name='markets_meta')
    op.drop_table('markets_meta')
    
    op.execute('DROP TYPE orderside;')
    op.execute('DROP TYPE orderstatus;')
    # ### end Alembic commands ###
